
# github action to update data
name: Update Data
on:
  schedule:
    - cron: '12 3 * * *'
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cralwer  data 
        run: |
            python -m cnstats -t --dbcode hgyd
            python -m cnstats -t --dbcode hgnd
            python -m cnstats --download --dbcode hgnd
            python -m cnstats --download --dbcode hgyd
      - name: Commit files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update data"
          git push

          


        